### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: microsoft.quantum.environment
summary: >-
  現在借用で使用可能な qubits の数を返します。

  これには未使用の qubits が含まれます。つまり、これにはによって返される qubits が含まれ `GetQubitsAvailableToUse` ます。
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      ステートメントで割り当てることができる qubits の数 `borrowing` 。

      使用されているターゲットコンピューターがこの情報を提供していない場合 `-1` は、が返されます。
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 18e68548e9f344a70dac95f70528a8b3e87f5909
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91478071"
