### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: microsoft.quantum.canon
summary: >-
  2つの関数の合成を返します。


  $ および $g $ $f 2 つの関数が指定されている場合、$f-circ g $ を表す新しい関数を返します。
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: 適用する2番目の関数。
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: 適用される最初の関数。
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: $、$F (g (x)) = h (x) $ のすべての入力 $x の新しい関数 $h $。
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: 適用する最初の関数の入力型。
- uid: "'U"
  summary: 適用される最初の関数の出力型と、適用する2番目の関数の入力型。
- uid: "'V"
  summary: 適用する2番目の関数の出力型。
metadata:
  ms.openlocfilehash: e62937fd42cb4067ca7a7947cac29a9ef539da6c
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89356747"
