### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft... 環境
summary: " # <a name=\"summary\"></a>Summary\n これらの関数は、クォンタムの計算が発生している環境に関する情報を提供します。"
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    現在借用で使用可能な qubits の数を返します。

    これには未使用の qubits が含まれます。つまり、これには `GetQubitsAvailableToUse`によって返される qubits が含まれます。
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: 現在使用できる qubits の数を返します。
ms.openlocfilehash: 50e5cfb7c1b9a4075c25b2705d00b435a09e159e
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 10/30/2019
ms.locfileid: "73056826"
