### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: 現在借用で使用可能な qubits の数を返します。
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: 現在使用できる qubits の数を返します。
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: これらの関数は、クォンタムの計算が発生している環境に関する情報を提供します。
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201446"
