### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  現在借用で使用可能な qubits の数を返します。

  これには未使用の qubits が含まれます。つまり、これには `GetQubitsAvailableToUse`によって返される qubits が含まれます。
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      `borrowing` ステートメントで割り当てることができる qubits の数。

      使用されているターゲットコンピューターでこの情報が提供されていない場合は、`-1` が返されます。
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
ms.openlocfilehash: c0caf866ad9a8773aa11ee7c6951ca3acc60cbaa
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 10/31/2019
ms.locfileid: "73230485"
