### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  現在借用で使用可能な qubits の数を返します。

  これには未使用の qubits が含まれます。つまり、これには `GetQubitsAvailableToUse`によって返される qubits が含まれます。
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      `borrowing` ステートメントで割り当てることができる qubits の数。

      使用されているターゲットコンピューターでこの情報が提供されていない場合は、`-1` が返されます。
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: c0caf866ad9a8773aa11ee7c6951ca3acc60cbaa
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73230485"
